IF DB_ID('ASRS_Warehouse') IS NULL
    CREATE DATABASE ASRS_Warehouse;
GO
USE ASRS_Warehouse;
GO

IF OBJECT_ID('movement_history','U') IS NOT NULL DROP TABLE movement_history;
IF OBJECT_ID('sensor_readings','U') IS NOT NULL DROP TABLE sensor_readings;
IF OBJECT_ID('WAREHOUSE_SLOTS','U') IS NOT NULL DROP TABLE WAREHOUSE_SLOTS;
GO

CREATE TABLE WAREHOUSE_SLOTS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(20) NOT NULL UNIQUE,
    RowNo INT NOT NULL,
    ColNo INT NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'EMPTY',
    SensorOccupied BIT NOT NULL DEFAULT 0,
    LastSensorUpdate DATETIME2 NULL,
    RequestType NVARCHAR(20) NULL,
    RequestedAt DATETIME2 NULL,
    CONSTRAINT CK_SLOT_STATUS CHECK (Status IN ('EMPTY','OCCUPIED','REQUEST')),
    CONSTRAINT CK_REQUEST_TYPE CHECK (RequestType IS NULL OR RequestType IN ('INBOUND','OUTBOUND'))
);
GO

CREATE TABLE sensor_readings (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    SlotId INT NOT NULL,
    Occupied BIT NOT NULL,
    RecordedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT FK_SENSOR_SLOT FOREIGN KEY (SlotId) REFERENCES WAREHOUSE_SLOTS(Id)
);
GO

CREATE TABLE movement_history (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    SlotId INT NOT NULL,
    MovementType NVARCHAR(20) NOT NULL,
    Result NVARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    Description NVARCHAR(255) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT CK_MOVEMENT_TYPE CHECK (MovementType IN ('INBOUND','OUTBOUND')),
    CONSTRAINT FK_HISTORY_SLOT FOREIGN KEY (SlotId) REFERENCES WAREHOUSE_SLOTS(Id)
);
GO

INSERT INTO WAREHOUSE_SLOTS(Name,RowNo,ColNo,Status,SensorOccupied) VALUES
('R01',1,1,'EMPTY',0),('R02',1,2,'EMPTY',0),('R03',1,3,'EMPTY',0),('R04',1,4,'EMPTY',0),
('R05',2,1,'EMPTY',0),('R06',2,2,'EMPTY',0),('R07',2,3,'EMPTY',0),('R08',2,4,'EMPTY',0);
GO

SELECT * FROM WAREHOUSE_SLOTS;
